config/routes.rb
Rails.application.routes.draw do
  get 'estrellas'=>'estrellas#index',as: :estrellas
  get 'planeta'=>'planeta#index',as: :planeta
  resources :estrellas
  resources :planeta
  root 'bienvenido#inicio'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estrella.rb
class Estrella < ApplicationRecord
end

app/models/planetum.rb
class Planetum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def inicio
  end
end

app/controllers/estrellas_controller.rb
class EstrellasController < ApplicationController
  before_action :set_estrella, only: [:show, :edit, :update, :destroy]

  # GET /estrellas
  # GET /estrellas.json
  def index
    @estrellas = Estrella.all
  end

  # GET /estrellas/1
  # GET /estrellas/1.json
  def show
  end

  # GET /estrellas/new
  def new
    @estrella = Estrella.new
  end

  # GET /estrellas/1/edit
  def edit
  end

  # POST /estrellas
  # POST /estrellas.json
  def create
    @estrella = Estrella.new(estrella_params)

    respond_to do |format|
      if @estrella.save
        format.html { redirect_to @estrella, notice: 'Estrella was successfully created.' }
        format.json { render :show, status: :created, location: @estrella }
      else
        format.html { render :new }
        format.json { render json: @estrella.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estrellas/1
  # PATCH/PUT /estrellas/1.json
  def update
    respond_to do |format|
      if @estrella.update(estrella_params)
        format.html { redirect_to @estrella, notice: 'Estrella was successfully updated.' }
        format.json { render :show, status: :ok, location: @estrella }
      else
        format.html { render :edit }
        format.json { render json: @estrella.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estrellas/1
  # DELETE /estrellas/1.json
  def destroy
    @estrella.destroy
    respond_to do |format|
      format.html { redirect_to estrellas_url, notice: 'Estrella was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estrella
      @estrella = Estrella.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estrella_params
      params.require(:estrella).permit(:Nombre, :Descripcion)
    end
end

app/controllers/planeta_controller.rb
class PlanetaController < ApplicationController
  before_action :set_planetum, only: [:show, :edit, :update, :destroy]

  # GET /planeta
  # GET /planeta.json
  def index
    @planeta = Planetum.all
  end

  # GET /planeta/1
  # GET /planeta/1.json
  def show
  end

  # GET /planeta/new
  def new
    @planetum = Planetum.new
  end

  # GET /planeta/1/edit
  def edit
  end

  # POST /planeta
  # POST /planeta.json
  def create
    @planetum = Planetum.new(planetum_params)

    respond_to do |format|
      if @planetum.save
        format.html { redirect_to @planetum, notice: 'Planetum was successfully created.' }
        format.json { render :show, status: :created, location: @planetum }
      else
        format.html { render :new }
        format.json { render json: @planetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planeta/1
  # PATCH/PUT /planeta/1.json
  def update
    respond_to do |format|
      if @planetum.update(planetum_params)
        format.html { redirect_to @planetum, notice: 'Planetum was successfully updated.' }
        format.json { render :show, status: :ok, location: @planetum }
      else
        format.html { render :edit }
        format.json { render json: @planetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planeta/1
  # DELETE /planeta/1.json
  def destroy
    @planetum.destroy
    respond_to do |format|
      format.html { redirect_to planeta_url, notice: 'Planetum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planetum
      @planetum = Planetum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planetum_params
      params.require(:planetum).permit(:Nombre, :Descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/estrellas_helper.rb
module EstrellasHelper
end

app/helpers/planeta_helper.rb
module PlanetaHelper
end

app/views/bienvenido/inicio.html.erb
 

<h1>Bienvenido</h1>


<p>Astronomia</p>
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  
  <body>
     
       <div class="row">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="http://static.vix.com/es/sites/default/files/styles/large/public/btg/curiosidades.batanga.com/files/Cual-es-la-distancia-de-los-planetas-al-Sol-2.jpg?itok=zPfE-aCp" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Planetas</h4>
            <p class="card-text">Según la definición, el sistema solar consta de ocho planetas: Mercurio, Venus, Tierra, Marte, Júpiter, Saturno, Urano y Neptuno.</p>
           
          </div>
        </div>

        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="http://vignette2.wikia.nocookie.net/universo/images/b/b4/03012014131214.jpg/revision/latest?cb=20160112121550&path-prefix=es" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Estrellas</h4>
            <p class="card-text">Una estrella (del latín: stella) es una esfera luminosa de plasma que mantiene su forma gracias a su propia gravedad. La estrella más cercana a la Tierra es el Sol.</p>
            
          </div>
        </div>

       </div>
       <div class="row">

        
      </div>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>

app/views/estrellas/_form.html.erb
<%= form_with(model: estrella, local: true) do |form| %>
  <% if estrella.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estrella.errors.count, "error") %> prohibited this estrella from being saved:</h2>

      <ul>
      <% estrella.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre, id: :estrella_Nombre %>
  </div>

  <div class="field">
    <%= form.label :Descripcion %>
    <%= form.text_area :Descripcion, id: :estrella_Descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estrellas/edit.html.erb
<h1>Editing Estrella</h1>

<%= render 'form', estrella: @estrella %>

<%= link_to 'Show', @estrella %> |
<%= link_to 'Back', estrellas_path %>

app/views/estrellas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estrellas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estrellas.each do |estrella| %>
      <tr>
        <td><%= estrella.Nombre %></td>
        <td><%= estrella.Descripcion %></td>
        <td><%= link_to 'Show', estrella %></td>
        <td><%= link_to 'Edit', edit_estrella_path(estrella) %></td>
        <td><%= link_to 'Destroy', estrella, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estrella', new_estrella_path %>

app/views/estrellas/new.html.erb
<h1>New Estrella</h1>

<%= render 'form', estrella: @estrella %>

<%= link_to 'Back', estrellas_path %>

app/views/estrellas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estrella.Nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @estrella.Descripcion %>
</p>

<%= link_to 'Edit', edit_estrella_path(@estrella) %> |
<%= link_to 'Back', estrellas_path %>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Inicio', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Estrellas', estrellas_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Planetas', planeta_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
      
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      Examen<span class='light'>1</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Estrellas', estrellas_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Planetas', planeta_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>


<% end %>
   
    <title>Astronomia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
 


    <%= yield %>
  


  </body>
</html>

app/views/planeta/_form.html.erb
<%= form_with(model: planetum, local: true) do |form| %>
  <% if planetum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planetum.errors.count, "error") %> prohibited this planetum from being saved:</h2>

      <ul>
      <% planetum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre, id: :planetum_Nombre %>
  </div>

  <div class="field">
    <%= form.label :Descripcion %>
    <%= form.text_area :Descripcion, id: :planetum_Descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planeta/edit.html.erb
<h1>Editing Planetum</h1>

<%= render 'form', planetum: @planetum %>

<%= link_to 'Show', @planetum %> |
<%= link_to 'Back', planeta_path %>

app/views/planeta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planeta</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planeta.each do |planetum| %>
      <tr>
        <td><%= planetum.Nombre %></td>
        <td><%= planetum.Descripcion %></td>
        <td><%= link_to 'Show', planetum %></td>
        <td><%= link_to 'Edit', edit_planetum_path(planetum) %></td>
        <td><%= link_to 'Destroy', planetum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planetum', new_planetum_path %>

app/views/planeta/new.html.erb
<h1>New Planetum</h1>

<%= render 'form', planetum: @planetum %>

<%= link_to 'Back', planeta_path %>

app/views/planeta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @planetum.Nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @planetum.Descripcion %>
</p>

<%= link_to 'Edit', edit_planetum_path(@planetum) %> |
<%= link_to 'Back', planeta_path %>